---
- hosts: all
  become: false
  gather_facts: false
  tasks:

  - name: ICMP ping from Control Node to Remote Node
    delegate_to: localhost # or controlnode.example.com
    ansible.builtin.command: ping -c 2 "{{ inventory_hostname }}"
    # Because it is an reporting task
    changed_when: false 
    check_mode: false
    failed_when: false
    register: router_ping

  - name: Show Return Code
    debug:
      msg: "{{ router_ping.rc }}"