---
- name: Ping All hosts
  hosts: all
  become: false
  gather_facts: false
  vars:
    host1: srv-rhel-01
    
  tasks:

  - name: ICMP ping from Control Node to Remote Node
    delegate_to: "{{ inventory_hostname }}" # or controlnode.example.com
    command: ping -c 2 "{{ host1 }}"
    # Because it is an reporting task
    changed_when: false 
    check_mode: false
    failed_when: router_ping.rc == 1 or router_ping.rc > 2 # will result into success for rc 0 and rc 2
    register: router_ping

  - name: How did we do?
    ansible.builtin.debug:
      msg: "{{ router_ping.rc[0] }}"
    run_once: true

  - name: Show Return Code
    debug:
      msg: "{{ router_ping.rc }}"