---
- hosts: all
  become: true
  gather_facts: false
  tasks:

- name: ICMP ping from Control Node to Remote Node
  delegate_to: srvUnexpected scalar at node endYAML-rhel-01 # or controlnode.example.com
  ansible.builtin.command: ping -c1 {{ inventory_hostname }}
  loop: "{{ ansible_play_hosts_all }}"
  # Because it is an reporting task
  changed_when: false 
  check_mode: false
  failed_when: false
  register: router_ping

#- name: Show Return Code
#    debug:
#      msg: "{{ router_ping.rc }}"
#  run_once: true

- name: Format it a bit
      # Note: the docs for 'copy' say don't do this, to use template instead,
      # and there are reasons, but this suffices for posting purposes.
      # The 'content:' below should be in your template.
  copy:
  #  content: "{{router_ping.stdout[0]}"
    dest: "/tmp/{{inventory_hostname}}.txt"
    content: |
          --- PING REPORT ---
          {% for pr in router_ping.rc %}
          {{ pr.stdout_lines | first }}
          {{ pr.stdout_lines | last }}
          
          {% endfor %}
  run_once: true
  delegate_to: localhost