---
- name: check reachable hosts
  hosts: "{{groups['srv01']}}"
  gather_facts: no
  
  vars: 
    port: 22

  tasks:
      - name: "Teste de conectividade"
        shell: |
          telnet "{{ item }}" "{{ port }}"
          quit
        #timeout: 5
        loop: "{{groups['host02']}}"
        run_once: true
        changed_when: false 
        check_mode: false
        register: connection_out
        #failed_when: connection_out.rc == 1 or connection_out.rc > 2 # will result into success for rc 0 and rc 2
      
      - name: Resultado telnet 
        ansible.builtin.debug:
          msg: "{{ connection_out.rc }}"
      #  run_once: true
      
      - name: "Format it a bit"
        ansible.builtin.template:
          src: ping.j2
          dest: "/tmp/teste-yaml/telnet-{{inventory_hostname}}.csv"