---
- hosts: "{{groups['srv01'][1]}}"
  become: false
  gather_facts: false
  tasks:

- name: "ICMP ping from Control Node to Remote Node"
  #delegate_to: srv-rhel-01 # or controlnode.example.com
  ansible.builtin.command: ping -c1 "{{groups['host02']}}"
  loop: "{{ ansible_play_hosts_all }}"
  # Because it is an reporting task
  #changed_when: false 
  #check_mode: false
  failed_when: false
  register: router_ping

- name: "Show Return Code"
  debug:
    msg: "{{ router_ping.rc }}"
  run_once: true

