---
- name: Ping All hosts
  hosts: all
  become: false
  gather_facts: false
  vars:
    host1: srv-rhel-01
    
  tasks:
    - name: Ping each host
      ansible.builtin.command: ping -c2 "{{ inventory_hostname }}"
      run_once: true
      loop: "{{ ansible_play_hosts_all }}"
      delegate_to: "{{ host1 }}"
      register: ping_result
      failed_when: false


    - name: How did we do?
      ansible.builtin.debug:
        msg: "{{ ping_result.results[0] }}"
      run_once: true