---
- name: Ping All hosts
  hosts: all
  roles:
    - role: 
      srv-01: "{{ groups['srv-01'] | map('extract',hostvars,'ansible_host') | list }}"
      host-fin: "{{ groups['host-fin'] | map('extract',hostvars,'ansible_host') | list }}"
  gather_facts: no
  tasks:
    - name: Ping each host
      command: ping -c 2 "{{ host-fin }}"
      run_once: true
      loop: "{{ srv-01 }}"
      delegate_to: localhost
      register: ping_result
      failed_when: false

    - name: How did we do?
      ansible.builtin.debug:
        msg: "{{ ping_result.results[0] }}"
      run_once: true