---
- hosts: "{{groups['srv01']}}"
  become: false
  gather_facts: false
  tasks:

  - name: ICMP ping from Control Node to Remote Node
    delegate_to: srv-rhel-01 # or controlnode.example.com
    command: ping -c 1 "{{groups['host02']}}"
    loop: "{{ ansible_play_hosts_all }}"
    # Because it is an reporting task
    changed_when: false 
    check_mode: false
    failed_when: router_ping.rc == 1 or router_ping.rc > 2 # will result into success for rc 0 and rc 2
    register: router_ping

  - name: Show Return Code
    debug:
      msg: "{{ router_ping.rc }}"