---
- name: Ping All hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping each host
      command: ping -c 2 "{{ item }}"
      run_once: true
      loop: "{{ ansible_play_hosts_all }}"
      delegate_to: localhost
      register: ping_result
      failed_when: false

    - name: How did we do?
      ansible.builtin.debug:
        msg: "{{ ping_result.results[0] }}"
      run_once: true