---
- name: check reachable hosts
  hosts: "{{groups['srv01']}}"
  gather_facts: no
  tasks:
      - name: Ping each host
        ansible.builtin.command: ping -c3 "{{ item }}"
        run_once: true
        loop: "{{groups['host02']}}"
      #delegate_to: localhost
        register: ping_result
        failed_when: false
      
      - name: check connectivity over port "{{ port_number }}"
        ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 1433
        timeout: 5
        loop:  "{{ target_hosts }}"
        register: connection_out
      
      - name: How did we do?
        ansible.builtin.debug:
          msg: "{{ ping_result.results[0] }}"
          msg1: "{{ connection_out.results [0] }}"
        run_once: true

      - name: "Format it a bit"
        # Note: the docs for 'copy' say don't do this, to use template instead,
        # and there are reasons, but this suffices for posting purposes.
        # The 'content:' below should be in your template.
        ansible.builtin.template:
          src: ping.j2
          dest: "/tmp/teste-yaml/{{inventory_hostname}}.csv"
#        run_once: true
        #delegate_to: localhost