---
- name: check reachable hosts
  hosts: "{{groups['srv01']}}"
  gather_facts: no
  tasks:
      - name: Ping each host
        ansible.builtin.command: ping -c1 "{{ item }}"
        run_once: true
        loop: "{{groups['host02']}}"
      #delegate_to: localhost
        register: ping_result
        failed_when: false

      - name: How did we do?
        ansible.builtin.debug:
          msg: "{{ ping_result.results[0] }}"
        run_once: true

- name: "Format it a bit"
    # Note: the docs for 'copy' say don't do this, to use template instead,
    # and there are reasons, but this suffices for posting purposes.
    # The 'content:' below should be in your template.
  ansible.builtin.copy:
    dest: "/tmp/teste-yaml/{{inventory_hostname}}.txt"
    content: |
      --- PING REPORT ---
      {% for pr in ping_result.results %}
      Host atual = {{ pr.item  }}
      {{ pr.stdout_lines | first }}
      {{ pr.stdout_lines[1] }}

      {% endfor %}
  run_once: true
  delegate_to: localhost

#    - name: Format cvs
#      template: src=/tmp/teste-yaml/ping.txt dest=./to_nice_yaml.output>
#      run_once: true
#      delegate_to: localhost
