---
- name: Ping All hosts
  hosts:
    host1: srv-rhel-01
    host2: host-fin

  gather_facts: no
  tasks:
    - name: Ping each host
      command: ping -c 2 "{{ host2 }}"
      run_once: true
      loop: "{{ ansible_play_hosts_all }}"
      delegate_to: "{{ host1 }}"
      register: ping_result
      failed_when: false

    - name: How did we do?
      ansible.builtin.debug:
        msg: "{{ ping_result.results[0] }}"
      run_once: true