---
- name: check reachable hosts
  hosts: "{{groups['srv1']}}"
  gather_facts: no
  
  vars: 
    port: 1433

  tasks:
      - name: "Teste de conectividade"
        command: telnet "{{ item }}" "{{ port }}"    
        loop:  "{{groups['host02']}}"
        run_once: true
        register: connection_out
      
      - name: Resultado telnet 
        ansible.builtin.debug:
          msg: "{{ connection_out.results[0] }}"
        run_once: true
      
      - name: "Format it a bit"
        ansible.builtin.template:
          src: ping.j2
          dest: "/tmp/teste-yaml/telnet-{{inventory_hostname}}.csv"